import { DSGConfig, EnvironmentType } from './types';

export const devConfig: DSGConfig = {
  env: 'dev' as EnvironmentType,
  aws: {
    account: process.env.AWS_ACCOUNT_ID || '',
    region: process.env.AWS_REGION || 'us-east-1',
  },
  tags: {
    Environment: 'dev',
    ManagedBy: 'CDK',
    Project: 'DSG-ONE',
    CostCenter: 'Engineering',
  },
  networking: {
    vpcCidr: '10.0.0.0/16',
    maxAzs: 2,
    natGateways: 1,
    enableFlowLogs: true,
    flowLogsRetentionDays: 7,
  },
  compute: {
    ecs: {
      enableExecuteCommand: true,
      enableContainerInsights: true,
    },
    desiredCount: 1,
    minCapacity: 1,
    maxCapacity: 2,
    taskCpu: 256,
    taskMemory: 512,
    enableAutoScaling: false,
    deploymentStrategy: 'ROLLING',
  },
  security: {
    kmsKeyRotation: true,
    enableWaf: false,
    enableShield: false,
    enableGuardDuty: true,
    enableSecurityHub: true,
    enableInspector: true,
    mfaRequired: false,
    sessionDurationHours: 8,
  },
  observability: {
    cloudWatchRetentionDays: 7,
    enableXRay: true,
    enableCloudTrail: true,
    cloudTrailRetentionDays: 7,
    enableDetailedMonitoring: true,
    logLevel: 'DEBUG',
  },
  governance: {
    policyEngineEnabled: true,
    approvalRequired: false,
    replayProofRequired: false,
    evidenceRetentionDays: 30,
    auditLogRetentionDays: 30,
    immutableAuditEnabled: false,
  },
  compliance: {
    iso42001: false,
    nistAiRmf: false,
    euAiAct: false,
    soc2: false,
    complianceReportingEnabled: false,
    policyAsCodeEnabled: true,
  },
  finops: {
    budgetAlertThreshold: 500,
    enableCostAnomaly: false,
    enableComputeOptimizer: false,
    enableRightsizing: false,
    savingsPlans: false,
  },
  features: {
    multiRegion: false,
    multiTenant: false,
    featureFlagsEnabled: true,
    canaryDeployments: false,
    blueGreenDeployments: false,
    workspaceIsolation: false,
  },
};
