import { DSGConfig, EnvironmentType } from './types';

export const prodConfig: DSGConfig = {
  env: 'prod' as EnvironmentType,
  aws: {
    account: process.env.AWS_ACCOUNT_ID || '',
    region: process.env.AWS_REGION || 'us-east-1',
    secondaryRegion: 'us-west-2',
  },
  tags: {
    Environment: 'prod',
    ManagedBy: 'CDK',
    Project: 'DSG-ONE',
    CostCenter: 'Operations',
  },
  networking: {
    vpcCidr: '10.2.0.0/16',
    maxAzs: 3,
    natGateways: 3,
    enableFlowLogs: true,
    flowLogsRetentionDays: 90,
  },
  compute: {
    ecs: {
      enableExecuteCommand: false,
      enableContainerInsights: true,
    },
    desiredCount: 3,
    minCapacity: 3,
    maxCapacity: 10,
    taskCpu: 1024,
    taskMemory: 2048,
    enableAutoScaling: true,
    deploymentStrategy: 'CANARY',
  },
  security: {
    kmsKeyRotation: true,
    enableWaf: true,
    enableShield: true,
    enableGuardDuty: true,
    enableSecurityHub: true,
    enableInspector: true,
    mfaRequired: true,
    sessionDurationHours: 2,
  },
  observability: {
    cloudWatchRetentionDays: 90,
    enableXRay: true,
    enableCloudTrail: true,
    cloudTrailRetentionDays: 365,
    enableDetailedMonitoring: true,
    logLevel: 'WARN',
  },
  governance: {
    policyEngineEnabled: true,
    approvalRequired: true,
    replayProofRequired: true,
    evidenceRetentionDays: 2555,
    auditLogRetentionDays: 2555,
    immutableAuditEnabled: true,
  },
  compliance: {
    iso42001: true,
    nistAiRmf: true,
    euAiAct: true,
    soc2: true,
    complianceReportingEnabled: true,
    policyAsCodeEnabled: true,
  },
  finops: {
    budgetAlertThreshold: 10000,
    enableCostAnomaly: true,
    enableComputeOptimizer: true,
    enableRightsizing: true,
    savingsPlans: true,
  },
  features: {
    multiRegion: true,
    multiTenant: true,
    featureFlagsEnabled: true,
    canaryDeployments: true,
    blueGreenDeployments: true,
    workspaceIsolation: true,
  },
};
