import { DSGConfig, EnvironmentType } from './types';

export const stagingConfig: DSGConfig = {
  env: 'staging' as EnvironmentType,
  aws: {
    account: process.env.AWS_ACCOUNT_ID || '',
    region: process.env.AWS_REGION || 'us-east-1',
    secondaryRegion: 'us-west-2',
  },
  tags: {
    Environment: 'staging',
    ManagedBy: 'CDK',
    Project: 'DSG-ONE',
    CostCenter: 'Engineering',
  },
  networking: {
    vpcCidr: '10.1.0.0/16',
    maxAzs: 2,
    natGateways: 2,
    enableFlowLogs: true,
    flowLogsRetentionDays: 30,
  },
  compute: {
    ecs: {
      enableExecuteCommand: true,
      enableContainerInsights: true,
    },
    desiredCount: 2,
    minCapacity: 2,
    maxCapacity: 4,
    taskCpu: 512,
    taskMemory: 1024,
    enableAutoScaling: true,
    deploymentStrategy: 'BLUE_GREEN',
  },
  security: {
    kmsKeyRotation: true,
    enableWaf: true,
    enableShield: false,
    enableGuardDuty: true,
    enableSecurityHub: true,
    enableInspector: true,
    mfaRequired: true,
    sessionDurationHours: 4,
  },
  observability: {
    cloudWatchRetentionDays: 30,
    enableXRay: true,
    enableCloudTrail: true,
    cloudTrailRetentionDays: 30,
    enableDetailedMonitoring: true,
    logLevel: 'INFO',
  },
  governance: {
    policyEngineEnabled: true,
    approvalRequired: true,
    replayProofRequired: true,
    evidenceRetentionDays: 90,
    auditLogRetentionDays: 90,
    immutableAuditEnabled: true,
  },
  compliance: {
    iso42001: true,
    nistAiRmf: true,
    euAiAct: false,
    soc2: false,
    complianceReportingEnabled: true,
    policyAsCodeEnabled: true,
  },
  finops: {
    budgetAlertThreshold: 2000,
    enableCostAnomaly: true,
    enableComputeOptimizer: true,
    enableRightsizing: true,
    savingsPlans: false,
  },
  features: {
    multiRegion: true,
    multiTenant: false,
    featureFlagsEnabled: true,
    canaryDeployments: true,
    blueGreenDeployments: true,
    workspaceIsolation: false,
  },
};
