"""
Runs all Z3 proofs and writes lib/gateway/verified-constraints.json.

Usage (from repo root):
    pip install z3-solver
    python3 lib/gateway/z3/generate_spec.py
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))

import z3
from theorems import main as run_policy_theorems
from defi_constraints import (
    main as run_defi_theorems,
    ALLOWED_TOKENS,
    ALLOWED_PROTOCOLS,
    MAX_SINGLE_TX_USD,
    MAX_DAILY_USD,
    MAX_SLIPPAGE_BPS,
)


def main():
    print('=' * 60)
    print('  Z3 Formal Verification — Governed Agent Execution Layer')
    print('=' * 60)

    print('\n── Core Policy Theorems (lib/gateway/policy.ts) ──────────')
    policy_proved = run_policy_theorems()

    print('\n── DeFi Transaction Constraints ──────────────────────────')
    defi_proved = run_defi_theorems()

    all_theorems = policy_proved + defi_proved
    print()
    print('=' * 60)
    print(f'  Total: {len(all_theorems)} theorems proved')
    print('=' * 60)

    def to_int(zval):
        return int(str(zval))

    spec = {
        '_comment': 'Machine-generated by lib/gateway/z3/generate_spec.py — do not edit manually',
        'version': '1.0.0',
        'z3Version': z3.get_version_string(),
        'theorems': all_theorems,
        'writeRoles': [
            'owner', 'admin', 'finance_admin', 'finance_approver', 'agent_operator'
        ],
        'executionPlans': ['enterprise', 'business', 'pro'],
        'defi': {
            'maxSingleTxUSD': to_int(MAX_SINGLE_TX_USD),
            'maxDailyUSD': to_int(MAX_DAILY_USD),
            'maxSlippageBps': to_int(MAX_SLIPPAGE_BPS),
            'allowedTokens': ALLOWED_TOKENS,
            'allowedProtocols': ALLOWED_PROTOCOLS,
        },
    }

    out_path = os.path.normpath(
        os.path.join(os.path.dirname(__file__), '..', 'verified-constraints.json')
    )
    with open(out_path, 'w') as f:
        json.dump(spec, f, indent=2)
        f.write('\n')

    print(f'\nWrote: {out_path}')
    print('All proofs passed. TypeScript DeFi validator is formally verified.')


if __name__ == '__main__':
    main()
