/**
 * Hermes Plugin Scaffold for DSG Brain.
 * Hermes proposes/remediates plans; all execution goes through Controlled Executor.
 * No direct DB write, no production claim, no raw secret exposure.
 * LLM integration uses server-side API keys only.
 */

import Anthropic from "@anthropic-ai/sdk";
import { PlanAttempt, buildPlanAttempt, PlanAttemptInput } from "./plan-attempt";
import {
  ControlledExecutionContext,
  ControlledExecutionResult,
  CredentialBrokerResult,
  buildControlledExecutionContext,
  buildExecutionGrant,
  renewExecutionGrant,
  renewCredentialLease,
  isGrantValid,
  isLeaseValid,
} from "./controlled-executor";
import { checkConformance, ConformanceReport } from "./conformance-gate";
import { brokerCredentials, CredentialBrokerConfig } from "./credential-broker";

/**
 * Hermes planning proposal.
 */
export interface HermesPlanProposal {
  /** The proposed plan attempt */
  plan: PlanAttempt;
  /** Human-readable rationale */
  rationale: string;
  /** Risk assessment tags */
  riskTags: string[];
}

/**
 * Hermes remediation proposal when a plan fails conformance.
 */
export interface HermesRemediation {
  /** Original plan that failed */
  originalPlan: PlanAttempt;
  /** Remediated plan attempt */
  remediatedPlan: PlanAttempt;
  /** Description of what was changed */
  changes: string[];
}

/**
 * Hermes plugin configuration.
 */
export interface HermesPluginConfig {
  /** Maximum number of remediation retries */
  maxRemediationAttempts: number;
  /** Default allowed commands whitelist */
  defaultAllowedCommands: string[];
  /** Default allowed paths whitelist */
  defaultAllowedPaths: string[];
  /** Default grant TTL in milliseconds */
  defaultGrantTtlMs: number;
  /** Default max grant renewals */
  defaultMaxRenewals: number;
  /** Grace period for lease/grant expiry in milliseconds */
  gracePeriodMs: number;
  /** Credential broker configuration */
  credentialBrokerConfig?: Partial<CredentialBrokerConfig>;
}

/**
 * Default Hermes plugin config.
 */
export const DEFAULT_HERMES_CONFIG: HermesPluginConfig = {
  maxRemediationAttempts: 3,
  defaultAllowedCommands: [],
  defaultAllowedPaths: [],
  defaultGrantTtlMs: 5 * 60 * 1000,
  defaultMaxRenewals: 2,
  gracePeriodMs: 30_000,
};

/**
 * Hermes Plugin for DSG Brain.
 * Orchestrates plan proposal and controlled execution.
 */
export class HermesPlugin {
  private config: HermesPluginConfig;

  constructor(config: Partial<HermesPluginConfig> = {}) {
    this.config = { ...DEFAULT_HERMES_CONFIG, ...config };
  }

  /**
   * Broker credentials for a set of secret names.
   * Queries Supabase for stored secrets and issues credential leases.
   * Never exposes raw secret values.
   *
   * @param secretNames Array of secret names to broker (e.g., "ANTHROPIC_API_KEY")
   * @returns CredentialBrokerResult with leases and unavailable list
   * @throws Error if credential brokering fails
   */
  async brokerCredentials(secretNames: string[]): Promise<CredentialBrokerResult> {
    return brokerCredentials(secretNames, this.config.credentialBrokerConfig);
  }

  /**
   * Propose a plan from raw input using Anthropic API.
   * Server-side only: API key never exposed to client.
   */
  async proposePlan(input: PlanAttemptInput): Promise<HermesPlanProposal> {
    const plan = buildPlanAttempt(input);
    const riskTags: string[] = [];

    // Check for incomplete plans
    if (plan.canonicalPlan.includes('TODO') || plan.canonicalPlan.includes('pending')) {
      riskTags.push('incomplete');
    }

    try {
      // Initialize Anthropic client with server-side API key only
      const apiKey = process.env.ANTHROPIC_API_KEY;
      if (!apiKey) {
        console.warn('[Hermes] ANTHROPIC_API_KEY not configured, using scaffold plan');
        riskTags.push('scaffold', 'pending-llm');
        return {
          plan,
          rationale: "Plan generated by Hermes scaffold (LLM not configured).",
          riskTags,
        };
      }

      const client = new Anthropic({ apiKey });

      // Request LLM to generate plan rationale and risk assessment
      const message = await client.messages.create({
        model: "claude-opus-4-1",
        max_tokens: 500,
        messages: [
          {
            role: "user",
            content: `Analyze this execution plan and provide:
1. Risk assessment (comma-separated tags like: 'high-privilege', 'file-system', 'network', etc.)
2. Brief rationale (1-2 sentences)

Plan:
${plan.canonicalPlan}

Respond in format:
RISKS: tag1, tag2, tag3
RATIONALE: Your rationale here`
          }
        ]
      });

      // Parse LLM response
      const response = message.content[0]?.type === 'text' ? message.content[0].text : '';
      const riskMatch = response.match(/RISKS:\s*(.+?)(?:\n|$)/);
      const rationaleMatch = response.match(/RATIONALE:\s*(.+?)$/m);

      if (riskMatch?.[1]) {
        const llmRisks = riskMatch[1].split(',').map(r => r.trim()).filter(Boolean);
        riskTags.push(...llmRisks);
      }

      const rationale = rationaleMatch?.[1] || `Plan proposed by Hermes with deterministic proposal hash ${plan.planHash}`;

      return {
        plan,
        rationale,
        riskTags: [...new Set(riskTags)] // Deduplicate
      };
    } catch (err) {
      console.error('[Hermes] LLM proposal failed:', err instanceof Error ? err.message : String(err));
      // Fallback to scaffold plan on LLM error
      riskTags.push('scaffold', 'llm-error');
      return {
        plan,
        rationale: "Plan generated by Hermes scaffold (LLM error).",
        riskTags,
      };
    }
  }

  /**
   * Remediate a plan that failed conformance using LLM-driven suggestions.
   */
  async remediatePlan(
    original: PlanAttempt,
    conformanceReport: ConformanceReport
  ): Promise<HermesRemediation> {
    const changes: string[] = [];
    let remediatedPlan = original.canonicalPlan;

    try {
      // Initialize Anthropic client with server-side API key only
      const apiKey = process.env.ANTHROPIC_API_KEY;
      if (!apiKey) {
        // Fallback: annotate with violations but don't call LLM
        changes.push(...conformanceReport.violations.map((v) => v.message));
        const remediatedInput: PlanAttemptInput = {
          inputHash: original.inputHash,
          attemptNo: original.attemptNo + 1,
          canonicalPlan: original.canonicalPlan + "\n\n[REMEDIATION VIOLATIONS]\n" + changes.join("\n"),
          policyVersion: original.policyVersion,
          invariantVersion: original.invariantVersion,
          toolManifestHash: original.toolManifestHash,
        };
        return {
          originalPlan: original,
          remediatedPlan: buildPlanAttempt(remediatedInput),
          changes,
        };
      }

      const client = new Anthropic({ apiKey });

      // Request LLM to suggest remediation
      const message = await client.messages.create({
        model: "claude-opus-4-1",
        max_tokens: 1000,
        messages: [
          {
            role: "user",
            content: `A plan failed conformance checks. Suggest modifications to fix it.

Original Plan:
${original.canonicalPlan}

Violations:
${conformanceReport.violations.map((v) => `- ${v.message}`).join("\n")}

Provide a remediated plan that addresses these violations. Keep the structure similar but modify problematic sections.`
          }
        ]
      });

      const remediationSuggestion = message.content[0]?.type === 'text' ? message.content[0].text : '';

      if (remediationSuggestion) {
        remediatedPlan = remediationSuggestion;
        changes.push(`LLM-generated remediation based on ${conformanceReport.violations.length} violation(s)`);
      }
    } catch (err) {
      console.error('[Hermes] LLM remediation failed:', err instanceof Error ? err.message : String(err));
      // Fallback: annotate violations
      changes.push(...conformanceReport.violations.map((v) => v.message));
    }

    const remediatedInput: PlanAttemptInput = {
      inputHash: original.inputHash,
      attemptNo: original.attemptNo + 1,
      canonicalPlan: remediatedPlan,
      policyVersion: original.policyVersion,
      invariantVersion: original.invariantVersion,
      toolManifestHash: original.toolManifestHash,
    };

    return {
      originalPlan: original,
      remediatedPlan: buildPlanAttempt(remediatedInput),
      changes,
    };
  }

  /**
   * Build a controlled execution context for an approved plan.
   * This is the ONLY way Hermes/OpenHands execution should run.
   * No direct DB write; all changes go through the Controlled Executor.
   */
  buildExecutionContext(
    plan: PlanAttempt,
    credentials: CredentialBrokerResult,
    overrides?: {
      allowedCommands?: string[];
      allowedPaths?: string[];
      ttlMs?: number;
      maxRenewals?: number;
    }
  ): ControlledExecutionContext {
    return buildControlledExecutionContext(
      plan,
      overrides?.allowedCommands ?? this.config.defaultAllowedCommands,
      overrides?.allowedPaths ?? this.config.defaultAllowedPaths,
      credentials,
      overrides?.ttlMs ?? this.config.defaultGrantTtlMs,
      overrides?.maxRenewals ?? this.config.defaultMaxRenewals
    );
  }

  /**
   * Renew execution context grant and leases mid-execution.
   * Useful for long-running tasks to prevent TTL race conditions.
   */
  renewExecutionContext(
    ctx: ControlledExecutionContext,
    additionalTtlMs?: number
  ): ControlledExecutionContext {
    const newGrant = renewExecutionGrant(
      ctx.grant,
      ctx.plan,
      additionalTtlMs ?? this.config.defaultGrantTtlMs
    );

    const newCredentials: CredentialBrokerResult = {
      leases: ctx.credentials.leases.map((lease) =>
        renewCredentialLease(lease, additionalTtlMs ?? this.config.defaultGrantTtlMs)
      ),
      unavailable: ctx.credentials.unavailable,
    };

    return {
      ...ctx,
      grant: newGrant,
      credentials: newCredentials,
    };
  }

  /**
   * Validate execution result against the approved plan.
   * Returns conformance report; caller must BLOCK if not approved.
   */
  validateExecution(
    ctx: ControlledExecutionContext,
    result: ControlledExecutionResult
  ): ConformanceReport {
    return checkConformance(ctx, result);
  }

  /**
   * Execute a plan through the Controlled Executor.
   * This scaffold does not call Anthropic live.
   * Production status remains NO-GO until live health/readiness evidence exists.
   */
  async executePlan(
    ctx: ControlledExecutionContext,
    runner: (ctx: ControlledExecutionContext) => Promise<ControlledExecutionResult>
  ): Promise<{ result: ControlledExecutionResult; report: ConformanceReport }> {
    const result = await runner(ctx);
    const report = this.validateExecution(ctx, result);
    return { result, report };
  }
}

/**
 * Factory to create a HermesPlugin with environment-derived config.
 */
export function createHermesPlugin(
  env: NodeJS.ProcessEnv = process.env
): HermesPlugin {
  const allowedCommands = env.DSG_HERMES_ALLOWED_COMMANDS
    ? env.DSG_HERMES_ALLOWED_COMMANDS.split(",")
    : [];
  const allowedPaths = env.DSG_HERMES_ALLOWED_PATHS
    ? env.DSG_HERMES_ALLOWED_PATHS.split(",")
    : [];

  return new HermesPlugin({
    defaultAllowedCommands: allowedCommands,
    defaultAllowedPaths: allowedPaths,
  });
}
