/**
 * Hermes Plugin Scaffold for DSG Brain.
 * Hermes proposes/remediates plans; all execution goes through Controlled Executor.
 * No direct DB write, no production claim, no raw secret exposure.
 */

import { PlanAttempt, buildPlanAttempt, PlanAttemptInput } from "./plan-attempt";
import {
  ControlledExecutionContext,
  ControlledExecutionResult,
  CredentialBrokerResult,
  buildControlledExecutionContext,
  buildExecutionGrant,
  renewExecutionGrant,
  renewCredentialLease,
  isGrantValid,
  isLeaseValid,
} from "./controlled-executor";
import { checkConformance, ConformanceReport } from "./conformance-gate";

/**
 * Hermes planning proposal.
 */
export interface HermesPlanProposal {
  /** The proposed plan attempt */
  plan: PlanAttempt;
  /** Human-readable rationale */
  rationale: string;
  /** Risk assessment tags */
  riskTags: string[];
}

/**
 * Hermes remediation proposal when a plan fails conformance.
 */
export interface HermesRemediation {
  /** Original plan that failed */
  originalPlan: PlanAttempt;
  /** Remediated plan attempt */
  remediatedPlan: PlanAttempt;
  /** Description of what was changed */
  changes: string[];
}

/**
 * Hermes plugin configuration.
 */
export interface HermesPluginConfig {
  /** Maximum number of remediation retries */
  maxRemediationAttempts: number;
  /** Default allowed commands whitelist */
  defaultAllowedCommands: string[];
  /** Default allowed paths whitelist */
  defaultAllowedPaths: string[];
  /** Default grant TTL in milliseconds */
  defaultGrantTtlMs: number;
  /** Default max grant renewals */
  defaultMaxRenewals: number;
  /** Grace period for lease/grant expiry in milliseconds */
  gracePeriodMs: number;
}

/**
 * Default Hermes plugin config.
 */
export const DEFAULT_HERMES_CONFIG: HermesPluginConfig = {
  maxRemediationAttempts: 3,
  defaultAllowedCommands: [],
  defaultAllowedPaths: [],
  defaultGrantTtlMs: 5 * 60 * 1000,
  defaultMaxRenewals: 2,
  gracePeriodMs: 30_000,
};

/**
 * Hermes Plugin for DSG Brain.
 * Orchestrates plan proposal and controlled execution.
 */
export class HermesPlugin {
  private config: HermesPluginConfig;

  constructor(config: Partial<HermesPluginConfig> = {}) {
    this.config = { ...DEFAULT_HERMES_CONFIG, ...config };
  }

  /**
   * Propose a plan from raw input.
   * In a full implementation, this would call the LLM (Anthropic) via the
   * server-side API key. This scaffold returns a deterministic placeholder.
   */
  async proposePlan(input: PlanAttemptInput): Promise<HermesPlanProposal> {
    const plan = buildPlanAttempt(input);

    // TODO: Integrate with Anthropic API using server-side key only.
    // The API key is never exposed in model context or client-side.

    return {
      plan,
      rationale: "Plan generated by Hermes scaffold (LLM integration pending).",
      riskTags: ["scaffold", "pending-llm"],
    };
  }

  /**
   * Remediate a plan that failed conformance.
   */
  async remediatePlan(
    original: PlanAttempt,
    conformanceReport: ConformanceReport
  ): Promise<HermesRemediation> {
    // TODO: Implement LLM-driven remediation.
    // For now, return identity remediation with annotations.
    const remediatedInput: PlanAttemptInput = {
      inputHash: original.inputHash,
      attemptNo: original.attemptNo + 1,
      canonicalPlan: original.canonicalPlan + "\n\n[REMEDIATION NOTE]\n",
      policyVersion: original.policyVersion,
      invariantVersion: original.invariantVersion,
      toolManifestHash: original.toolManifestHash,
    };

    return {
      originalPlan: original,
      remediatedPlan: buildPlanAttempt(remediatedInput),
      changes: conformanceReport.violations.map((v) => v.message),
    };
  }

  /**
   * Build a controlled execution context for an approved plan.
   * This is the ONLY way Hermes/OpenHands execution should run.
   * No direct DB write; all changes go through the Controlled Executor.
   */
  buildExecutionContext(
    plan: PlanAttempt,
    credentials: CredentialBrokerResult,
    overrides?: {
      allowedCommands?: string[];
      allowedPaths?: string[];
      ttlMs?: number;
      maxRenewals?: number;
    }
  ): ControlledExecutionContext {
    return buildControlledExecutionContext(
      plan,
      overrides?.allowedCommands ?? this.config.defaultAllowedCommands,
      overrides?.allowedPaths ?? this.config.defaultAllowedPaths,
      credentials,
      overrides?.ttlMs ?? this.config.defaultGrantTtlMs,
      overrides?.maxRenewals ?? this.config.defaultMaxRenewals
    );
  }

  /**
   * Renew execution context grant and leases mid-execution.
   * Useful for long-running tasks to prevent TTL race conditions.
   */
  renewExecutionContext(
    ctx: ControlledExecutionContext,
    additionalTtlMs?: number
  ): ControlledExecutionContext {
    const newGrant = renewExecutionGrant(
      ctx.grant,
      ctx.plan,
      additionalTtlMs ?? this.config.defaultGrantTtlMs
    );

    const newCredentials: CredentialBrokerResult = {
      leases: ctx.credentials.leases.map((lease) =>
        renewCredentialLease(lease, additionalTtlMs ?? this.config.defaultGrantTtlMs)
      ),
      unavailable: ctx.credentials.unavailable,
    };

    return {
      ...ctx,
      grant: newGrant,
      credentials: newCredentials,
    };
  }

  /**
   * Validate execution result against the approved plan.
   * Returns conformance report; caller must BLOCK if not approved.
   */
  validateExecution(
    ctx: ControlledExecutionContext,
    result: ControlledExecutionResult
  ): ConformanceReport {
    return checkConformance(ctx, result);
  }

  /**
   * Execute a plan through the Controlled Executor.
   * This scaffold does not call Anthropic live.
   * Production status remains NO-GO until live health/readiness evidence exists.
   */
  async executePlan(
    ctx: ControlledExecutionContext,
    runner: (ctx: ControlledExecutionContext) => Promise<ControlledExecutionResult>
  ): Promise<{ result: ControlledExecutionResult; report: ConformanceReport }> {
    const result = await runner(ctx);
    const report = this.validateExecution(ctx, result);
    return { result, report };
  }
}

/**
 * Factory to create a HermesPlugin with environment-derived config.
 */
export function createHermesPlugin(
  env: NodeJS.ProcessEnv = process.env
): HermesPlugin {
  const allowedCommands = env.DSG_HERMES_ALLOWED_COMMANDS
    ? env.DSG_HERMES_ALLOWED_COMMANDS.split(",")
    : [];
  const allowedPaths = env.DSG_HERMES_ALLOWED_PATHS
    ? env.DSG_HERMES_ALLOWED_PATHS.split(",")
    : [];

  return new HermesPlugin({
    defaultAllowedCommands: allowedCommands,
    defaultAllowedPaths: allowedPaths,
  });
}
