import { NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';

export const dynamic = 'force-dynamic';

function getDsgUrl() {
  return process.env.DSG_ONE_V1_URL ?? 'https://dsg-one-v1.vercel.app';
}

async function ghFetch(token: string, path: string, opts?: RequestInit) {
  return fetch(`https://api.github.com${path}`, {
    ...opts,
    headers: {
      Authorization: `token ${token}`,
      Accept: 'application/vnd.github+json',
      'Content-Type': 'application/json',
      ...((opts?.headers as Record<string, string>) ?? {}),
    },
  });
}

function scaffoldFiles(goal: string, appName: string): Record<string, string> {
  const safeGoal = goal.slice(0, 200).replace(/`/g, "'");
  return {
    'README.md': `# ${appName}\n\nGenerated by [DSG ONE](https://dsg-one.com)\n\n## Goal\n\n${goal}\n\n## Getting Started\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n`,
    'package.json': JSON.stringify({
      name: appName, version: '0.1.0', private: true,
      scripts: { dev: 'next dev', build: 'next build', start: 'next start' },
      dependencies: { next: '15.0.0', react: '^19.0.0', 'react-dom': '^19.0.0' },
      devDependencies: { typescript: '^5', '@types/node': '^20', '@types/react': '^19', '@types/react-dom': '^19' },
    }, null, 2),
    'next.config.js': `/** @type {import('next').NextConfig} */\nconst nextConfig = {};\nmodule.exports = nextConfig;\n`,
    'app/layout.tsx': `import type { Metadata } from 'next';\nexport const metadata: Metadata = { title: '${appName}' };\nexport default function RootLayout({ children }: { children: React.ReactNode }) {\n  return <html lang="en"><body>{children}</body></html>;\n}\n`,
    'app/page.tsx': `export default function Home() {\n  return (\n    <main style={{ padding: '2rem', fontFamily: 'system-ui' }}>\n      <h1>${appName}</h1>\n      <p style={{ color: '#666', maxWidth: 600 }}>${safeGoal}</p>\n    </main>\n  );\n}\n`,
    '.gitignore': `.next/\nout/\nbuild/\nnode_modules/\n.env*.local\n*.log\n`,
  };
}

export async function POST(request: Request) {
  const supabase = await createClient();
  const { data: { session } } = await supabase.auth.getSession();
  if (!session) {
    return NextResponse.json({ ok: false, error: 'Unauthorized' }, { status: 401 });
  }

  const body = await request.json().catch(() => null) as {
    jobId?: string;
    repoName?: string;
    description?: string;
    githubToken?: string;
    private?: boolean;
  } | null;

  if (!body?.jobId) {
    return NextResponse.json({ ok: false, error: 'jobId required' }, { status: 400 });
  }

  const githubToken = body.githubToken ?? process.env.GITHUB_TOKEN;
  if (!githubToken) {
    return NextResponse.json({ ok: false, error: 'github_token required' }, { status: 400 });
  }

  let goal = `DSG ONE generated app (job ${body.jobId})`;
  try {
    const jobRes = await fetch(`${getDsgUrl()}/api/dsg/jobs/${body.jobId}`, {
      headers: { Authorization: `Bearer ${session.access_token}` },
    });
    if (jobRes.ok) {
      const jobData = await jobRes.json();
      if (jobData.data?.goal) goal = jobData.data.goal;
    }
  } catch {
    // use default goal
  }

  const userRes = await ghFetch(githubToken, '/user');
  const ghUser = await userRes.json();
  if (!ghUser.login) {
    return NextResponse.json({ ok: false, error: 'GITHUB_TOKEN_INVALID' }, { status: 401 });
  }

  const repoName = (body.repoName ?? `dsg-app-${body.jobId.slice(0, 8)}`)
    .replace(/[^a-z0-9-]/gi, '-').toLowerCase();
  const description = (body.description ?? goal).slice(0, 255);

  const createRes = await ghFetch(githubToken, '/user/repos', {
    method: 'POST',
    body: JSON.stringify({ name: repoName, description, private: body.private ?? false, auto_init: false }),
  });
  const repo = await createRes.json();

  if (!repo.html_url) {
    return NextResponse.json({ ok: false, error: repo.message ?? 'GITHUB_CREATE_REPO_FAILED' }, { status: 400 });
  }

  const fullRepo = `${ghUser.login}/${repoName}`;
  const files = scaffoldFiles(goal, repoName);

  for (const [filePath, content] of Object.entries(files)) {
    await ghFetch(githubToken, `/repos/${fullRepo}/contents/${filePath}`, {
      method: 'PUT',
      body: JSON.stringify({
        message: 'feat: DSG ONE generated scaffold',
        content: Buffer.from(content).toString('base64'),
      }),
    }).catch(() => {});
  }

  return NextResponse.json({
    ok: true,
    data: {
      jobId: body.jobId,
      repoUrl: repo.html_url,
      repoName,
      owner: ghUser.login,
      filesCreated: Object.keys(files).length,
    },
  });
}
