import type { Metadata } from 'next';
import Link from 'next/link';
import { GATE_PLANS } from '@/lib/billing/pricing-catalog';
import { UpgradeCTA } from '../../_components/UpgradeCTA';
import { ShareSection } from './ShareSection';

export const dynamic = 'force-dynamic';

interface ReportData {
  ok: boolean;
  claim_pass_eligible: boolean | null;
  run_id: string | null;
  mutation_score: number | null;
  requirements_pass: number | null;
  requirements_total: number;
  last_ci_run: string | null;
  updated_at: string | null;
  shield: { label: string; message: string; color: string };
  deployment: { commit: string; env: string; policy_version: string };
}

async function fetchReport(runId: string): Promise<ReportData | null> {
  const base =
    process.env.NEXT_PUBLIC_APP_URL ??
    process.env.APP_URL ??
    'https://tdealer01-crypto-dsg-control-plane.vercel.app';
  try {
    const res = await fetch(`${base}/api/ccvs/compliance-status?run_id=${encodeURIComponent(runId)}`, {
      cache: 'no-store',
    });
    if (!res.ok) return null;
    const data = await res.json() as ReportData;
    if (!data.ok || !data.run_id) return null;
    return data;
  } catch {
    return null;
  }
}

function claimLabel(eligible: boolean | null): { label: string; color: string; bg: string } {
  if (eligible === null) return { label: 'PENDING', color: 'text-slate-300', bg: 'border-slate-400/30 bg-slate-400/10' };
  if (eligible) return { label: 'EVIDENCE COMPLETE', color: 'text-emerald-200', bg: 'border-emerald-400/30 bg-emerald-400/10' };
  return { label: 'PRODUCTION BLOCKED', color: 'text-red-200', bg: 'border-red-400/30 bg-red-400/10' };
}

export async function generateMetadata({ params }: { params: Promise<{ run_id: string }> }): Promise<Metadata> {
  const { run_id } = await params;
  const base =
    process.env.NEXT_PUBLIC_APP_URL ??
    process.env.APP_URL ??
    'https://tdealer01-crypto-dsg-control-plane.vercel.app';
  const reportUrl = `${base}/delivery-proof/report/${encodeURIComponent(run_id)}`;

  return {
    title: `Delivery Proof Report — ${run_id} — DSG ONE`,
    description: 'Shareable AI code delivery proof report generated by DSG ONE CCVS v1.2. Verify pre-audit evidence for production deployment.',
    openGraph: {
      title: `Delivery Proof Report — ${run_id}`,
      description: 'AI governance proof: pre-execution gate, deterministic audit trail, CCVS v1.2 compliance evidence.',
      url: reportUrl,
      type: 'website',
      siteName: 'DSG ONE',
      images: [
        {
          url: `${base}/og/delivery-proof.png`, // Placeholder - will create OG image
          width: 1200,
          height: 630,
          alt: `DSG ONE Delivery Proof Report — ${run_id}`,
        },
      ],
    },
    twitter: {
      card: 'summary_large_image',
      title: `Delivery Proof Report — ${run_id}`,
      description: 'Verified AI governance evidence for production deployment.',
      images: [`${base}/og/delivery-proof.png`],
    },
    robots: {
      index: true,
      follow: true,
    },
  };
}

export default async function DeliveryProofReportPage({ params }: { params: Promise<{ run_id: string }> }) {
  const { run_id } = await params;
  const report = await fetchReport(run_id);

  if (!report) {
    return (
      <main className="min-h-screen bg-[#07080a] text-white">
        <section className="border-b border-white/10 bg-[#0b0d10]">
          <div className="mx-auto max-w-3xl px-6 py-12">
            <p className="text-[11px] uppercase tracking-[0.3em] text-slate-500">DSG ONE · Delivery Proof Report</p>
            <h1 className="mt-3 text-3xl font-bold text-white">Report Not Found</h1>
            <p className="mt-2 font-mono text-sm text-slate-400">run_id: {run_id}</p>
            <div className="mt-8 rounded-2xl border border-amber-400/30 bg-amber-400/10 px-6 py-5">
              <p className="text-sm text-amber-200">
                This report may have been generated before persistent storage was enabled, or the run_id is invalid.
                Run a new proof scan to generate a fresh shareable report.
              </p>
            </div>
            <div className="mt-8 flex flex-wrap gap-3">
              <Link href="/delivery-proof" className="rounded-xl bg-emerald-400 px-5 py-3 text-sm font-bold text-slate-950 hover:bg-emerald-300">
                Run New Scan →
              </Link>
              <Link href="/" className="rounded-xl border border-white/15 px-5 py-3 text-sm font-semibold text-slate-200 hover:border-white/30">
                ← Home
              </Link>
            </div>
          </div>
        </section>
      </main>
    );
  }

  const claim = claimLabel(report.claim_pass_eligible);
  const passRate = report.requirements_pass !== null && report.requirements_total
    ? `${report.requirements_pass}/${report.requirements_total}`
    : 'n/a';

  return (
    <main className="min-h-screen bg-[#07080a] text-white">
      <section className="border-b border-white/10 bg-[#0b0d10]">
        <div className="mx-auto max-w-3xl px-6 py-12">
          <p className="text-[11px] uppercase tracking-[0.3em] text-slate-500">DSG ONE · Delivery Proof Report</p>
          <h1 className="mt-3 text-3xl font-bold text-white">Proof Report</h1>
          <p className="mt-1 font-mono text-sm text-slate-400">run_id: {report.run_id}</p>

          {/* Claim result */}
          <div className={`mt-8 rounded-2xl border px-6 py-5 ${claim.bg}`}>
            <p className="text-[11px] uppercase tracking-[0.25em] text-slate-400">Claim Result</p>
            <p className={`mt-2 text-3xl font-bold ${claim.color}`}>{claim.label}</p>
            {report.claim_pass_eligible !== null && (
              <p className="mt-2 text-sm text-slate-400">
                {report.claim_pass_eligible
                  ? 'All CCVS requirements passed — evidence complete for pre-audit submission.'
                  : 'One or more CCVS requirements not met — review required before production claim.'}
              </p>
            )}
          </div>

          {/* Metrics */}
          <div className="mt-6 grid gap-4 md:grid-cols-3">
            <div className="border border-white/10 bg-white/[0.03] p-5">
              <p className="text-[11px] uppercase tracking-[0.22em] text-slate-500">Requirements</p>
              <p className="mt-2 text-2xl font-bold text-white">{passRate}</p>
              <p className="text-xs text-slate-500">pass / total</p>
            </div>
            <div className="border border-white/10 bg-white/[0.03] p-5">
              <p className="text-[11px] uppercase tracking-[0.22em] text-slate-500">Mutation Score</p>
              <p className="mt-2 text-2xl font-bold text-white">
                {report.mutation_score !== null ? `${report.mutation_score}%` : 'n/a'}
              </p>
              <p className="text-xs text-slate-500">Stryker · gate ≥70%</p>
            </div>
            <div className="border border-white/10 bg-white/[0.03] p-5">
              <p className="text-[11px] uppercase tracking-[0.22em] text-slate-500">Environment</p>
              <p className="mt-2 text-2xl font-bold text-white">{report.deployment.env}</p>
              <p className="font-mono text-xs text-slate-500">{report.deployment.commit.slice(0, 8)}</p>
            </div>
          </div>

          {/* Timestamps */}
          <div className="mt-4 grid gap-4 md:grid-cols-2">
            <div className="border border-white/10 bg-white/[0.03] p-4">
              <p className="text-[11px] uppercase tracking-[0.22em] text-slate-500">Last CI Run</p>
              <p className="mt-1 font-mono text-sm text-slate-300">{report.last_ci_run ?? 'n/a'}</p>
            </div>
            <div className="border border-white/10 bg-white/[0.03] p-4">
              <p className="text-[11px] uppercase tracking-[0.22em] text-slate-500">Report Updated</p>
              <p className="mt-1 font-mono text-sm text-slate-300">{report.updated_at ?? 'n/a'}</p>
            </div>
          </div>

          {/* Evidence links */}
          <div className="mt-8 border border-white/10 bg-white/[0.03] p-5">
            <p className="text-[11px] uppercase tracking-[0.25em] text-slate-500">Evidence Endpoints</p>
            <div className="mt-3 space-y-2 font-mono text-sm text-slate-300">
              <p>GET /api/ccvs/evidence-chain</p>
              <p>GET /api/compliance-evidence-pack/annex4</p>
              <p>GET /api/compliance-evidence-pack</p>
            </div>
          </div>

          {/* Disclaimer */}
          <div className="mt-6 border border-amber-300/20 bg-amber-300/5 p-4 text-xs text-amber-200/70">
            certificationClaim = false · independentAuditClaim = false ·
            This report is pre-audit evidence mapping for internal use only.
            Not a third-party certification or legal compliance guarantee.
          </div>

          {/* Upgrade CTA */}
          <div className="mt-8 border border-emerald-400/40 bg-emerald-400/10 rounded-2xl p-6">
            <p className="text-[11px] uppercase tracking-[0.25em] text-emerald-300">Get Certified</p>
            <h3 className="mt-3 text-2xl font-bold text-emerald-100">
              Share & Sell This Proof
            </h3>
            <p className="mt-2 text-sm text-emerald-200/80">
              Upgrade to Pro to unlock white-label branding, unlimited scans, and team access.
              Share this report with clients, auditors, or your team — each view reinforces governance credibility.
            </p>
            <div className="mt-4 grid gap-3 sm:grid-cols-2">
              <a
                href="/billing?plan=pro"
                className="rounded-xl bg-emerald-400 px-5 py-3 text-sm font-bold text-emerald-950 hover:bg-emerald-300 transition text-center"
              >
                Upgrade to Pro — ${GATE_PLANS.pro.displayMonthlyUsd}/mo →
              </a>
              <a
                href="/billing?plan=business"
                className="rounded-xl border border-emerald-300/50 bg-emerald-400/10 px-5 py-3 text-sm font-bold text-emerald-200 hover:bg-emerald-400/20 transition text-center"
              >
                Business Plan — ${GATE_PLANS.business.displayMonthlyUsd}/mo →
              </a>
            </div>
          </div>

          {/* Viral Share Section (client component — clipboard/window APIs) */}
          <ShareSection
            runId={report.run_id!}
            claimLabel={claim.label}
            passRate={passRate}
            mutationScore={report.mutation_score}
            environment={report.deployment.env}
          />

          {/* Upgrade CTA */}
          <UpgradeCTA runId={report.run_id || ''} isFreeUser={report.claim_pass_eligible !== true} currentTier="free" />
          <div className="mt-8 flex flex-wrap gap-3">
            <Link
              href={`/api/compliance-evidence-pack?run_id=${encodeURIComponent(report.run_id!)}`}
              target="_blank"
              className="rounded-xl bg-amber-300 px-5 py-3 text-sm font-bold text-slate-950 hover:bg-amber-200"
            >
              Full Evidence Pack PDF →
            </Link>
            <Link
              href="/delivery-proof"
              className="rounded-xl border border-white/15 px-5 py-3 text-sm font-semibold text-slate-200 hover:border-white/30"
            >
              ← Back to Delivery Proof
            </Link>
          </div>
        </div>
      </section>
    </main>
  );
}
