'use client';

import { useMemo, useState } from 'react';

interface ShareSectionProps {
  runId: string;
  claimLabel: string;
  passRate: string;
  mutationScore: number | null;
  environment: string;
}

export function ShareSection({ runId, claimLabel, passRate, mutationScore, environment }: ShareSectionProps) {
  const [copied, setCopied] = useState<'link' | 'badge' | null>(null);

  const reportUrl = useMemo(() => {
    if (typeof window !== 'undefined') return window.location.href;
    return `/delivery-proof/report/${encodeURIComponent(runId)}`;
  }, [runId]);

  const badgeMarkdown = useMemo(() => {
    const origin = typeof window !== 'undefined' ? window.location.origin : '';
    const badgeUrl = `${origin}/api/delivery-proof/badge/${encodeURIComponent(runId)}`;
    const pageUrl = `${origin}/delivery-proof/report/${encodeURIComponent(runId)}`;
    return `[![DSG Delivery Proof](${badgeUrl})](${pageUrl})`;
  }, [runId]);

  const copy = async (text: string, which: 'link' | 'badge') => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(which);
      setTimeout(() => setCopied(null), 2000);
    } catch {
      // clipboard unavailable — ignore
    }
  };

  return (
    <div className="mt-8 border border-emerald-400/20 bg-emerald-400/5 p-5 rounded-2xl">
      <p className="text-[11px] uppercase tracking-[0.25em] text-emerald-300">Share This Proof</p>
      <p className="mt-2 text-sm text-slate-300">
        This report is public and verifiable. Share it with clients, auditors, or your team —
        each view reinforces the credibility of pre-execution governance.
      </p>

      {/* Copy link + social */}
      <div className="mt-4 flex flex-wrap items-center gap-3">
        <button
          onClick={() => copy(reportUrl, 'link')}
          className="rounded-xl border border-white/10 bg-white/5 px-4 py-2.5 text-sm font-semibold text-white hover:border-emerald-400/50 transition"
          title="Copy report link"
        >
          {copied === 'link' ? '✅ Copied' : '📋 Copy Link'}
        </button>

        <a
          href={`https://twitter.com/intent/tweet?text=${encodeURIComponent(
            `✅ Delivery Proof: ${claimLabel} — ${passRate} requirements passed via DSG ONE pre-execution gate`,
          )}&url=${encodeURIComponent(reportUrl)}`}
          target="_blank"
          rel="noopener noreferrer"
          className="rounded-xl border border-white/10 bg-white/5 px-4 py-2.5 text-sm font-semibold text-white hover:border-sky-400/50 transition"
        >
          🐦 Share on X
        </a>

        <a
          href={`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(reportUrl)}`}
          target="_blank"
          rel="noopener noreferrer"
          className="rounded-xl border border-white/10 bg-white/5 px-4 py-2.5 text-sm font-semibold text-white hover:border-blue-400/50 transition"
        >
          💼 Share on LinkedIn
        </a>

        <a
          href={`mailto:?subject=${encodeURIComponent(
            `DSG ONE Delivery Proof Report — ${claimLabel}`,
          )}&body=${encodeURIComponent(
            `View this AI governance proof report:\n${reportUrl}\n\nClaim: ${claimLabel}\nRequirements: ${passRate}\nMutation Score: ${mutationScore !== null ? `${mutationScore}%` : 'n/a'}\nEnvironment: ${environment}\n\nGenerated by DSG ONE CCVS v1.2`,
          )}`}
          className="rounded-xl border border-white/10 bg-white/5 px-4 py-2.5 text-sm font-semibold text-white hover:border-amber-400/50 transition"
        >
          📧 Email
        </a>
      </div>

      {/* Embed badge in README */}
      <div className="mt-5 rounded-xl border border-emerald-400/20 bg-black/30 p-4">
        <p className="text-[11px] uppercase tracking-[0.2em] text-emerald-300">Embed This Badge</p>
        <p className="mt-1 text-xs text-slate-400">
          Add a live proof badge to your README. It always reflects the current status of this scan.
        </p>
        <div className="mt-3 flex flex-wrap items-center gap-3">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={`/api/delivery-proof/badge/${encodeURIComponent(runId)}`}
            alt={`DSG Delivery Proof badge — ${claimLabel}`}
            height={20}
          />
          <button
            onClick={() => copy(badgeMarkdown, 'badge')}
            className="rounded-lg border border-emerald-400/40 bg-emerald-400/10 px-3 py-2 text-xs font-semibold text-emerald-200 hover:bg-emerald-400/20 transition"
          >
            {copied === 'badge' ? '✅ Copied markdown' : '📋 Copy markdown'}
          </button>
        </div>
        <pre className="mt-3 overflow-x-auto rounded-lg bg-black/50 p-3 font-mono text-[11px] leading-relaxed text-slate-300">
          {badgeMarkdown}
        </pre>
      </div>

      {/* Growth loop note */}
      <div className="mt-4 p-3 rounded-xl bg-emerald-400/10 border border-emerald-400/20">
        <p className="text-xs text-emerald-200">
          🔁 <strong>Growth loop:</strong> Every share and badge drives viral acquisition — viewers see verified
          proof and can run their own scan at <code className="font-mono text-emerald-300 mx-1">/delivery-proof</code>.
        </p>
      </div>

      {/* QR + verification links */}
      <div className="mt-4 flex items-center justify-center gap-4 flex-wrap">
        <div className="text-center">
          <div className="inline-block bg-white p-2 rounded">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={`https://api.qrserver.com/v1/create-qr-code/?size=120x120&data=${encodeURIComponent(reportUrl)}`}
              alt={`QR code for ${runId}`}
              loading="lazy"
              className="block"
              width={120}
              height={120}
            />
          </div>
          <p className="mt-2 text-xs text-slate-400">Scan to open on mobile</p>
        </div>

        <div className="flex-1 min-w-[200px] border border-emerald-400/30 bg-emerald-400/10 rounded-2xl p-4">
          <p className="text-[11px] uppercase tracking-[0.2em] text-emerald-300 text-center">✅ Verifiable</p>
          <p className="mt-1 text-center text-sm text-emerald-200">
            This report is public and independently verifiable.
          </p>
          <div className="mt-3 flex flex-wrap justify-center gap-2">
            <a
              href={`/api/ccvs/evidence-chain?run_id=${encodeURIComponent(runId)}`}
              target="_blank"
              rel="noopener noreferrer"
              className="text-xs text-emerald-300 hover:underline mx-auto"
            >
              View Evidence Chain
            </a>
            <span className="text-xs text-slate-500">|</span>
            <a
              href={`/api/compliance-evidence-pack/annex4?run_id=${encodeURIComponent(runId)}`}
              target="_blank"
              rel="noopener noreferrer"
              className="text-xs text-emerald-300 hover:underline mx-auto"
            >
              View Annex IV Mapping
            </a>
          </div>
        </div>
      </div>
    </div>
  );
}
