'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import {
  CheckCircle2,
  Circle,
  ChevronDown,
  ChevronUp,
  X,
  Plug,
  Zap,
  FileSearch,
  Users,
  GitMerge,
  Archive,
} from 'lucide-react';

const STORAGE_KEY_DISMISSED = 'dsg_cp_onboarding_dismissed';
const STORAGE_KEY_STEPS = 'dsg_cp_onboarding_steps';

type Step = {
  id: string;
  icon: React.ComponentType<{ className?: string }>;
  title: string;
  description: string;
  cta: { label: string; href: string };
  storageFlag?: string;
};

const STEPS: Step[] = [
  {
    id: 'connect_integration',
    icon: Plug,
    title: 'Connect your first integration',
    description: 'Link an external service so DSG can govern its actions.',
    cta: { label: 'Go to integrations', href: '/dashboard/integration' },
    storageFlag: 'dsg_cp_visited_integration',
  },
  {
    id: 'run_governed_action',
    icon: Zap,
    title: 'Run a governed action',
    description: 'Execute an action through the ProofGate control layer.',
    cta: { label: 'Open command center', href: '/dashboard/command-center' },
    storageFlag: 'dsg_cp_visited_command_center',
  },
  {
    id: 'review_evidence',
    icon: FileSearch,
    title: 'Review evidence pack',
    description: 'Inspect the cryptographic proof generated by your action.',
    cta: { label: 'View evidence', href: '/evidence-pack' },
    storageFlag: 'dsg_cp_visited_evidence',
  },
  {
    id: 'setup_team',
    icon: Users,
    title: 'Set up team members',
    description: 'Invite operators and assign roles for your workspace.',
    cta: { label: 'Manage team', href: '/dashboard/team' },
    storageFlag: 'dsg_cp_visited_team',
  },
  {
    id: 'configure_approval',
    icon: GitMerge,
    title: 'Configure approval workflow',
    description: 'Define who must approve high-risk actions before execution.',
    cta: { label: 'Set up approvals', href: '/approvals' },
    storageFlag: 'dsg_cp_visited_approvals',
  },
  {
    id: 'export_audit_pack',
    icon: Archive,
    title: 'Export your first audit pack',
    description: 'Generate a signed audit export for compliance records.',
    cta: { label: 'Export now', href: '/evidence-pack' },
    storageFlag: 'dsg_cp_visited_export',
  },
];

export function OnboardingChecklist() {
  const [dismissed, setDismissed] = useState(false);
  const [collapsed, setCollapsed] = useState(false);
  const [completed, setCompleted] = useState<Set<string>>(new Set());
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
    const isDismissed = localStorage.getItem(STORAGE_KEY_DISMISSED) === 'true';
    setDismissed(isDismissed);

    const raw = localStorage.getItem(STORAGE_KEY_STEPS);
    const saved: string[] = raw ? JSON.parse(raw) : [];

    const autoCompleted = new Set(saved);
    for (const step of STEPS) {
      if (step.storageFlag && localStorage.getItem(step.storageFlag) === 'true') {
        autoCompleted.add(step.id);
      }
    }
    setCompleted(autoCompleted);
  }, []);

  function dismiss() {
    localStorage.setItem(STORAGE_KEY_DISMISSED, 'true');
    setDismissed(true);
  }

  function toggleStep(id: string) {
    setCompleted((prev) => {
      const next = new Set(prev);
      if (next.has(id)) {
        next.delete(id);
      } else {
        next.add(id);
      }
      localStorage.setItem(STORAGE_KEY_STEPS, JSON.stringify([...next]));
      return next;
    });
  }

  if (!mounted || dismissed) return null;

  const total = STEPS.length;
  const done = STEPS.filter((s) => completed.has(s.id)).length;
  const progress = Math.round((done / total) * 100);

  return (
    <div className="fixed bottom-6 right-6 z-50 w-80 rounded-3xl border border-white/10 bg-[#0b0d10] shadow-2xl shadow-black/70">
      {/* Header */}
      <div
        className="flex cursor-pointer items-center justify-between gap-3 rounded-t-3xl border-b border-white/10 px-4 py-3 select-none"
        onClick={() => setCollapsed((c) => !c)}
      >
        <div className="flex items-center gap-2">
          <span className="text-sm font-bold text-white">Get started with DSG</span>
          <span className="rounded-full border border-[#D4AF37]/30 bg-[#D4AF37]/10 px-2 py-0.5 text-xs font-semibold text-[#F5D76E]">
            {done}/{total}
          </span>
        </div>
        <div className="flex items-center gap-2">
          {collapsed ? (
            <ChevronUp className="h-4 w-4 text-slate-400" />
          ) : (
            <ChevronDown className="h-4 w-4 text-slate-400" />
          )}
          <button
            onClick={(e) => {
              e.stopPropagation();
              dismiss();
            }}
            className="rounded-md p-0.5 text-slate-500 transition hover:bg-white/[0.06] hover:text-slate-200"
            aria-label="Dismiss"
          >
            <X className="h-4 w-4" />
          </button>
        </div>
      </div>

      {/* Progress bar */}
      {!collapsed && (
        <div className="h-0.5 w-full bg-white/[0.06]">
          <div
            className="h-0.5 bg-[#D4AF37] transition-all duration-500"
            style={{ width: `${progress}%` }}
          />
        </div>
      )}

      {/* Steps */}
      {!collapsed && (
        <div className="divide-y divide-white/[0.06] px-1 py-1">
          {STEPS.map((step) => {
            const Icon = step.icon;
            const isComplete = completed.has(step.id);
            return (
              <div key={step.id} className="flex items-start gap-3 rounded-2xl px-3 py-3">
                <button
                  onClick={() => toggleStep(step.id)}
                  className="mt-0.5 shrink-0 text-slate-500 transition hover:text-[#D4AF37]"
                  aria-label={isComplete ? 'Mark incomplete' : 'Mark complete'}
                >
                  {isComplete ? (
                    <CheckCircle2 className="h-5 w-5 text-emerald-400" />
                  ) : (
                    <Circle className="h-5 w-5" />
                  )}
                </button>
                <div className="min-w-0 flex-1">
                  <div className="flex items-center gap-2">
                    <Icon className="h-3.5 w-3.5 shrink-0 text-[#D4AF37]" />
                    <p
                      className={`text-sm font-semibold leading-5 ${
                        isComplete ? 'text-slate-600 line-through' : 'text-slate-100'
                      }`}
                    >
                      {step.title}
                    </p>
                  </div>
                  {!isComplete && (
                    <p className="mt-0.5 text-xs leading-4 text-slate-500">{step.description}</p>
                  )}
                  {!isComplete && (
                    <Link
                      href={step.cta.href}
                      className="mt-1.5 inline-block rounded-xl border border-[#D4AF37]/25 bg-[#D4AF37]/10 px-2.5 py-1 text-xs font-semibold text-[#F5D76E] transition hover:bg-[#D4AF37]/20"
                    >
                      {step.cta.label} →
                    </Link>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* Footer when all done */}
      {!collapsed && done === total && (
        <div className="px-4 pb-4 pt-2 text-center">
          <p className="text-xs font-semibold text-emerald-400">All steps complete — your workspace is ready.</p>
          <button
            onClick={dismiss}
            className="mt-2 rounded-xl border border-white/10 bg-white/[0.04] px-4 py-1.5 text-xs font-semibold text-slate-300 transition hover:bg-white/[0.08]"
          >
            Dismiss
          </button>
        </div>
      )}
    </div>
  );
}
