import { runOpenAIAdapter } from '@/lib/dsg/ai/openai-adapter';
import type { AppBuilderJob } from './model';
import type { AppBuilderRuntimeHandoff } from './runtime-handoff';

type GeneratedFile = {
  path: string;
  content: string;
  evidenceKind: 'frontend' | 'backend_api' | 'database_migration' | 'documentation';
};

type AiAppBlueprint = {
  title: string;
  summary: string;
  appKind: string;
  primaryEntity: string;
  primaryInputLabel: string;
  emptyState: string;
  actions: string[];
  evidenceLabels: string[];
  apiPathName: string;
  tableName: string;
  theme: 'enterprise' | 'cyber' | 'finance' | 'operations';
  truthBoundary: string;
};

function safeSegment(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9-]/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '').slice(0, 48) || 'app';
}

function timestampForMigration(now = new Date()) {
  return now.toISOString().replace(/[-:T.Z]/g, '').slice(0, 14);
}

function compact(value: string, max = 1200) {
  return value.replace(/\s+/g, ' ').trim().slice(0, max);
}

function jsonString(value: unknown) {
  return JSON.stringify(value);
}

function extractJsonObject(value: string) {
  const trimmed = value.trim();
  const fenced = trimmed.match(/```(?:json)?\s*([\s\S]*?)```/i)?.[1]?.trim();
  const source = fenced || trimmed;
  const start = source.indexOf('{');
  const end = source.lastIndexOf('}');
  if (start < 0 || end <= start) throw new Error('AI_BLUEPRINT_JSON_NOT_FOUND');
  return JSON.parse(source.slice(start, end + 1)) as Record<string, unknown>;
}

function stringArray(value: unknown, fallback: string[]) {
  if (!Array.isArray(value)) return fallback;
  const items = value.filter((item): item is string => typeof item === 'string').map((item) => compact(item, 90)).filter(Boolean).slice(0, 8);
  return items.length ? items : fallback;
}

function validateBlueprint(input: Record<string, unknown>, job: AppBuilderJob): AiAppBlueprint {
  const title = typeof input.title === 'string' ? compact(input.title, 90) : job.prd?.title || 'Generated DSG App';
  const summary = typeof input.summary === 'string' ? compact(input.summary, 260) : job.prd?.summary || job.goal?.normalizedGoal || 'Generated governed app';
  const appKind = typeof input.appKind === 'string' ? safeSegment(input.appKind) : 'custom-app';
  const primaryEntity = typeof input.primaryEntity === 'string' ? compact(input.primaryEntity, 48) : 'record';
  const primaryInputLabel = typeof input.primaryInputLabel === 'string' ? compact(input.primaryInputLabel, 80) : `Create ${primaryEntity}`;
  const apiPathName = typeof input.apiPathName === 'string' ? safeSegment(input.apiPathName) : 'records';
  const rawTableName = typeof input.tableName === 'string' ? input.tableName : `generated_${safeSegment(primaryEntity).replace(/-/g, '_')}`;
  const tableName = rawTableName.toLowerCase().replace(/[^a-z0-9_]/g, '_').replace(/_+/g, '_').replace(/^_|_$/g, '').slice(0, 48) || 'generated_records';
  const theme = input.theme === 'cyber' || input.theme === 'finance' || input.theme === 'operations' ? input.theme : 'enterprise';

  return {
    title,
    summary,
    appKind,
    primaryEntity,
    primaryInputLabel,
    emptyState: typeof input.emptyState === 'string' ? compact(input.emptyState, 140) : `No ${primaryEntity} records yet.`,
    actions: stringArray(input.actions, ['Create governed record', 'Verify evidence', 'Export proof']),
    evidenceLabels: stringArray(input.evidenceLabels, ['planHash', 'approvalHash', 'apiStatus', 'auditEvent']),
    apiPathName,
    tableName,
    theme,
    truthBoundary: typeof input.truthBoundary === 'string' ? compact(input.truthBoundary, 260) : 'Generated by AI blueprint; implementation evidence only until runtime, database, and preview proof pass.',
  };
}

async function buildBlueprint(job: AppBuilderJob): Promise<AiAppBlueprint | null> {
  try {
    const result = await runOpenAIAdapter({
      temperature: 0.1,
      maxOutputTokens: 900,
      messages: [
        {
          role: 'developer',
          content: [
            'You generate a compact JSON blueprint for a Next.js generated app.',
            'Return JSON only. No markdown. No prose.',
            'Do not claim production-ready, deployed, certified, or verified unless evidence is provided.',
            'The generated app must reflect the user goal, not a generic todo/item app.',
            'Use enterprise wording and DSG evidence boundaries.',
            'Schema: { title, summary, appKind, primaryEntity, primaryInputLabel, emptyState, actions:string[], evidenceLabels:string[], apiPathName, tableName, theme, truthBoundary }',
          ].join('\n'),
        },
        {
          role: 'user',
          content: JSON.stringify({
            goal: job.goal?.normalizedGoal || job.goal?.originalGoal || job.prd?.summary || 'Generated governed app',
            successCriteria: job.goal?.successCriteria || job.prd?.acceptanceCriteria || [],
            constraints: job.goal?.constraints || job.prd?.nonGoals || [],
            prd: job.prd || null,
          }),
        },
      ],
    });
    return validateBlueprint(extractJsonObject(result.outputText), job);
  } catch {
    return null;
  }
}

function frontendContent(job: AppBuilderJob, handoff: AppBuilderRuntimeHandoff, blueprint: AiAppBlueprint) {
  const appId = jsonString(job.id);
  const title = jsonString(blueprint.title);
  const summary = jsonString(blueprint.summary);
  const entity = jsonString(blueprint.primaryEntity);
  const inputLabel = jsonString(blueprint.primaryInputLabel);
  const emptyState = jsonString(blueprint.emptyState);
  const actions = jsonString(blueprint.actions);
  const evidenceLabels = jsonString(blueprint.evidenceLabels);
  const apiPathName = jsonString(blueprint.apiPathName);
  const planHash = jsonString(handoff.planHash);
  const approvalHash = jsonString(handoff.approvalHash);
  const truthBoundary = jsonString(blueprint.truthBoundary);

  return `'use client';

import React, { useEffect, useState } from 'react';

type RecordRow = { id: string; app_id: string; title: string; status: string; evidence: Record<string, unknown>; created_at: string };

const APP_ID = ${appId};
const APP_TITLE = ${title};
const APP_SUMMARY = ${summary};
const PRIMARY_ENTITY = ${entity};
const INPUT_LABEL = ${inputLabel};
const EMPTY_STATE = ${emptyState};
const ACTIONS = ${actions} as string[];
const EVIDENCE_LABELS = ${evidenceLabels} as string[];
const API_PATH_NAME = ${apiPathName};
const PLAN_HASH = ${planHash};
const APPROVAL_HASH = ${approvalHash};
const TRUTH_BOUNDARY = ${truthBoundary};

export default function GeneratedDsgAppPage() {
  const [records, setRecords] = useState<RecordRow[]>([]);
  const [title, setTitle] = useState(INPUT_LABEL);
  const [status, setStatus] = useState('Loading governed backend evidence...');
  const [busy, setBusy] = useState(false);

  async function loadRecords() {
    setStatus('Loading governed backend evidence...');
    const response = await fetch(\`/api/generated-apps/\${APP_ID}/\${API_PATH_NAME}\`, { cache: 'no-store' });
    const json = await response.json();
    if (!response.ok || !json.ok) throw new Error(json.error?.message || 'GENERATED_APP_BACKEND_FAILED');
    setRecords(json.data.records);
    setStatus('Backend API + database table reachable');
  }

  async function createRecord() {
    const trimmed = title.trim();
    if (!trimmed || busy) return;
    setBusy(true);
    setStatus('Creating governed record...');
    try {
      const response = await fetch(\`/api/generated-apps/\${APP_ID}/\${API_PATH_NAME}\`, {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ title: trimmed, evidence: { planHash: PLAN_HASH, approvalHash: APPROVAL_HASH, source: 'generated-app-ui' } }),
      });
      const json = await response.json();
      if (!response.ok || !json.ok) throw new Error(json.error?.message || 'GENERATED_APP_CREATE_FAILED');
      setTitle('');
      await loadRecords();
    } finally {
      setBusy(false);
    }
  }

  useEffect(() => {
    loadRecords().catch((error) => setStatus(error instanceof Error ? error.message : 'GENERATED_APP_LOAD_FAILED'));
  }, []);

  return (
    <main className="min-h-screen bg-[#071326] px-4 py-6 text-[#F5F7FA] md:px-8">
      <div className="mx-auto max-w-6xl space-y-5">
        <section className="rounded-[2rem] border border-[#C8A24D] bg-[#0C2340] p-5 shadow-[0_0_48px_rgba(200,162,77,0.22)]">
          <p className="text-[11px] font-black uppercase tracking-[0.24em] text-[#E0B95B]">DSG AI-Generated Full-Stack App</p>
          <h1 className="mt-3 text-3xl font-black leading-tight md:text-5xl">{APP_TITLE}</h1>
          <p className="mt-3 max-w-3xl text-sm leading-7 text-[#D7D9DE]">{APP_SUMMARY}</p>
          <div className="mt-5 grid gap-3 text-xs font-mono md:grid-cols-2">
            <div className="rounded-2xl border border-[#C8A24D]/40 bg-[#071326] p-4">planHash: <span className="text-[#E0B95B]">{PLAN_HASH}</span></div>
            <div className="rounded-2xl border border-[#C8A24D]/40 bg-[#071326] p-4">approvalHash: <span className="text-[#E0B95B]">{APPROVAL_HASH}</span></div>
          </div>
        </section>

        <section className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_340px]">
          <div className="rounded-[2rem] border border-[#C8A24D] bg-[#F6F0E1] p-3">
            <div className="rounded-[1.5rem] bg-[#071326] p-4">
              <div className="flex flex-col gap-3 md:flex-row">
                <input value={title} onChange={(event) => setTitle(event.target.value)} className="min-h-12 flex-1 rounded-xl border border-[#C8A24D]/50 bg-[#0C2340] px-4 text-white outline-none" placeholder={INPUT_LABEL} />
                <button onClick={() => createRecord().catch((error) => setStatus(error instanceof Error ? error.message : 'GENERATED_APP_CREATE_FAILED'))} disabled={busy} className="rounded-xl border border-[#C8A24D] bg-[#E0B95B] px-5 py-3 font-black text-[#071326] disabled:opacity-50">{busy ? 'Running...' : 'Create'}</button>
              </div>
              <p className="mt-3 text-sm text-[#D7D9DE]">{status}</p>
              <div className="mt-4 space-y-3">
                {records.map((record) => (
                  <div key={record.id} className="rounded-2xl border border-[#C8A24D]/30 bg-[#0C2340] p-4">
                    <p className="font-black text-[#F5F7FA]">{record.title}</p>
                    <p className="mt-1 text-xs text-[#E0B95B]">{record.status}</p>
                    <p className="mt-1 text-xs text-[#D7D9DE]">{new Date(record.created_at).toLocaleString()}</p>
                  </div>
                ))}
                {!records.length ? <div className="rounded-2xl border border-dashed border-[#C8A24D]/40 p-6 text-sm text-[#D7D9DE]">{EMPTY_STATE}</div> : null}
              </div>
            </div>
          </div>

          <aside className="space-y-4">
            <section className="rounded-3xl border border-[#C8A24D] bg-[#0C2340] p-4">
              <p className="text-[11px] font-black uppercase tracking-[0.2em] text-[#E0B95B]">Governed Actions</p>
              <div className="mt-3 space-y-2">{ACTIONS.map((action) => <div key={action} className="rounded-xl border border-[#C8A24D]/30 bg-[#071326] p-3 text-sm">{action}</div>)}</div>
            </section>
            <section className="rounded-3xl border border-[#C8A24D] bg-[#0C2340] p-4">
              <p className="text-[11px] font-black uppercase tracking-[0.2em] text-[#E0B95B]">Evidence</p>
              <div className="mt-3 flex flex-wrap gap-2">{EVIDENCE_LABELS.map((label) => <span key={label} className="rounded-full border border-[#C8A24D]/40 px-3 py-1 text-xs text-[#E0B95B]">{label}</span>)}</div>
              <p className="mt-4 rounded-xl border border-[#D9363E]/40 bg-[#D9363E]/10 p-3 text-xs leading-5 text-[#ffb4b8]">{TRUTH_BOUNDARY}</p>
            </section>
          </aside>
        </section>
      </div>
    </main>
  );
}
`;
}

function apiContent(job: AppBuilderJob, blueprint: AiAppBlueprint) {
  const appId = jsonString(job.id);
  const tableName = blueprint.tableName;
  return `import { NextResponse } from 'next/server';

type SupabaseRequest = { method?: 'GET' | 'POST'; path: string; query?: string; body?: unknown };
type RecordRow = { id: string; app_id: string; title: string; status: string; evidence: Record<string, unknown>; created_at: string };

const APP_ID = ${appId};
const TABLE_NAME = '${tableName}';

function supabaseConfig() {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) throw new Error('GENERATED_APP_SUPABASE_ENV_REQUIRED');
  return { url: url.endsWith('/') ? url.slice(0, -1) : url, key };
}

async function supabaseRest<T>(input: SupabaseRequest): Promise<T> {
  const { url, key } = supabaseConfig();
  const response = await fetch(\`\${url}/rest/v1/\${input.path}\${input.query ?? ''}\`, {
    method: input.method ?? 'GET',
    headers: { apikey: key, authorization: \`Bearer \${key}\`, 'content-type': 'application/json', prefer: 'return=representation' },
    body: input.body === undefined ? undefined : JSON.stringify(input.body),
  });
  const text = await response.text();
  const data = text ? JSON.parse(text) : null;
  if (!response.ok) throw new Error(typeof data?.message === 'string' ? data.message : 'GENERATED_APP_SUPABASE_REQUEST_FAILED');
  return data as T;
}

function fail(error: unknown) {
  const message = error instanceof Error ? error.message : 'GENERATED_APP_REQUEST_FAILED';
  return NextResponse.json({ ok: false, error: { code: message, message } }, { status: 400 });
}

export async function GET() {
  try {
    const rows = await supabaseRest<RecordRow[]>({ path: TABLE_NAME, query: \`?app_id=eq.\${encodeURIComponent(APP_ID)}&select=id,app_id,title,status,evidence,created_at&order=created_at.desc\` });
    return NextResponse.json({ ok: true, data: { appId: APP_ID, records: rows } });
  } catch (error) {
    return fail(error);
  }
}

export async function POST(req: Request) {
  try {
    const body = (await req.json()) as { title?: string; evidence?: Record<string, unknown> };
    const title = body.title?.trim();
    if (!title) throw new Error('GENERATED_APP_TITLE_REQUIRED');
    const rows = await supabaseRest<RecordRow[]>({ method: 'POST', path: TABLE_NAME, body: { app_id: APP_ID, title, status: 'GOVERNED_CREATED', evidence: body.evidence || {} } });
    return NextResponse.json({ ok: true, data: { record: rows[0] } });
  } catch (error) {
    return fail(error);
  }
}
`;
}

function migrationContent(job: AppBuilderJob, blueprint: AiAppBlueprint) {
  return `-- Generated by DSG App Builder AI blueprint for job ${job.id}
-- Title: ${blueprint.title.replace(/\n/g, ' ')}

create extension if not exists pgcrypto;

create table if not exists ${blueprint.tableName} (
  id uuid primary key default gen_random_uuid(),
  app_id text not null,
  title text not null,
  status text not null default 'GOVERNED_CREATED',
  evidence jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ${blueprint.tableName}_app_id_created_at_idx
  on ${blueprint.tableName}(app_id, created_at desc);

alter table ${blueprint.tableName} enable row level security;
`;
}

function runbookContent(job: AppBuilderJob, handoff: AppBuilderRuntimeHandoff, blueprint: AiAppBlueprint) {
  return `# DSG AI-Generated App Evidence

- App Builder Job: \`${job.id}\`
- Workspace: \`${job.workspaceId}\`
- Blueprint Kind: \`${blueprint.appKind}\`
- Plan Hash: \`${handoff.planHash}\`
- Approval Hash: \`${handoff.approvalHash}\`
- Claim Status: \`IMPLEMENTED_UNVERIFIED\`

## Generated app

${blueprint.summary}

## Generated files

- Frontend: \`app/generated-apps/${job.id}/page.tsx\`
- API: \`app/api/generated-apps/${job.id}/${blueprint.apiPathName}/route.ts\`
- Migration table: \`${blueprint.tableName}\`

## Truth boundary

${blueprint.truthBoundary}

This PR is implementation evidence only. Do not claim DEPLOYABLE or PRODUCTION until CI, migration apply, deployment proof, and production-flow proof pass.
`;
}

export async function buildAiGenericGeneratedAppFiles(job: AppBuilderJob, handoff: AppBuilderRuntimeHandoff): Promise<GeneratedFile[] | null> {
  const blueprint = await buildBlueprint(job);
  if (!blueprint) return null;
  const appSlug = safeSegment(job.id);
  const migrationStamp = timestampForMigration();
  return [
    { path: `app/generated-apps/${appSlug}/page.tsx`, content: frontendContent(job, handoff, blueprint), evidenceKind: 'frontend' },
    { path: `app/api/generated-apps/${appSlug}/${blueprint.apiPathName}/route.ts`, content: apiContent(job, blueprint), evidenceKind: 'backend_api' },
    { path: `supabase/migrations/${migrationStamp}_create_${blueprint.tableName}_${appSlug.slice(0, 8)}.sql`, content: migrationContent(job, blueprint), evidenceKind: 'database_migration' },
    { path: `docs/dsg-generated-apps/${appSlug}.md`, content: runbookContent(job, handoff, blueprint), evidenceKind: 'documentation' },
  ];
}
