export const DSG_PHASE1_GOVERNANCE_PROMPT = [
  'DSG Phase 1 Connector Registry + Phase 1B Governance Automation:',
  '',
  'Use this reference when the user asks about connectors, external tools, webhooks, Zapier, Make, n8n, REST integrations, approval queues, governance automation, policy evaluation, risk routing, evidence manifests, replay hashes, or connector execution.',
  '',
  'Connector registry model:',
  '- gateway_connectors: connector configuration, provider, endpoint, risk level, owner team, automation mode, data classification, control profile.',
  '- gateway_tools: tool mappings for connectors, method, payload template, risk tags, allowed agent scopes, approval requirements.',
  '- gateway_execution_events: execution audit events with request hash, response hash, policy decision, status, approval id, evidence manifest, and replay hash.',
  '',
  'Connector API behavior:',
  '- Create connector config.',
  '- List connectors.',
  '- Create tool mapping.',
  '- List tool mappings.',
  '- Test connector reachability with secret redaction.',
  '- Execute connector through policy and audit.',
  '- Execute tools through agent-style alias.',
  '- Read one execution event.',
  '- Read execution audit log.',
  '',
  'Governance automation modes:',
  '- shadow: evaluate and record only, do not call external system.',
  '- gated: auto-run low risk and create approval requests for high/critical risk. This is the default enterprise posture.',
  '- autopilot: auto-run only where policy explicitly allows; still block or review high/critical risk unless approval exists.',
  '',
  'Governance runtime sequence:',
  '- Agent/UI submits tool execution request.',
  '- Render payload template from input.',
  '- Classify risk from provider, method, payload sensitivity, endpoint, connector base risk, and critical keywords.',
  '- Evaluate policies.',
  '- block: store rejected audit event.',
  '- review: create approval request and store waiting_approval event. Do not call the external endpoint.',
  '- observe: store observed event and skip external call.',
  '- allow: call controlled connector, hash response, store evidence manifest and replay hash.',
  '',
  'Risk classifier signals:',
  '- Mutation method POST/PUT/PATCH/DELETE raises risk.',
  '- DELETE is destructive and high risk.',
  '- Sensitive fields include password, secret, token, authorization, api_key, payment, billing, refund, charge, card, bank, customer, email, phone, address, pii, admin, role.',
  '- Unsupported providers increase risk.',
  '- Invalid endpoint increases risk.',
  '- Critical keywords include payment, refund, charge, deploy, production, admin, role, permission.',
  '',
  'Policy decisions:',
  '- allow: execution may proceed through controlled connector call.',
  '- block: deny and record rejected audit event.',
  '- review: create approval request; no external call until approval is resolved.',
  '- observe: shadow-mode record-only outcome.',
  '',
  'Evidence requirements:',
  '- Every governed execution should expose request hash, response hash if a call happened, policy hash or policy trace, evidence manifest, replay hash, decision, risk level, approval id if any, and status.',
  '- Auth headers or secrets must be redacted in UI and test responses.',
  '',
  'Production blockers from the patch:',
  '- Real workspace auth/RBAC on every gateway route is still required.',
  '- Secrets must move to a secret manager or encrypted vault before production.',
  '- Alembic/Postgres migration evidence is required for real DB deployment.',
  '- Approval execution resume flow must rerun the original request using the stored approval request.',
  '- CI evidence is required: backend tests, frontend build, container smoke, and real webhook integration proof.',
  '',
  'Truth status:',
  '- Treat this patch as BUILDABLE reference / implementation pattern unless repo integration, migration, RBAC, secret vault, CI, and live integration proof exist.',
  '- Do not claim production-ready governance automation from this patch alone.',
].join('\n');

export function shouldUsePhase1Governance(message: string) {
  return /connector|registry|webhook|zapier|make|n8n|rest|tool mapping|gateway|governance automation|approval queue|policy evaluation|risk classification|risk classifier|evidence manifest|replay hash|request hash|response hash|automation dashboard|shadow|gated|autopilot|integration|external tool|เครื่องมือภายนอก|คอนเนคเตอร์|อนุมัติ|นโยบาย|ความเสี่ยง/i.test(message);
}

export function buildPhase1GovernanceInstruction(userMessage: string) {
  return [
    'Apply DSG Phase 1 Connector Registry and Phase 1B Governance Automation reference if the user asks about connectors, tools, external integrations, approval flow, policy gates, evidence manifests, or replay hashes.',
    'Use the patch as a design/contract source unless the current Next.js repo has integrated and verified the implementation.',
    'Do not claim production completion without RBAC, secret vault, migrations, CI/build/test, and live connector proof.',
    `Current user message: ${userMessage}`,
  ].join('\n');
}
