#!/bin/bash

################################################################################
# DSG ONE Final Setup - Step 2-4
# Update Secrets + Create .env + Deploy CDK
################################################################################

set -euo pipefail

# Colors
BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $*"; }
log_success() { echo -e "${GREEN}[✓]${NC} $*"; }
log_warn() { echo -e "${YELLOW}[!]${NC} $*"; }
log_error() { echo -e "${RED}[✗]${NC} $*"; exit 1; }

ENVIRONMENT="${1:-dev}"
AWS_REGION="ap-southeast-1"  # ตรงกับ region ที่ script ก่อนหน้าสร้าง
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "=================================="
log_info "🚀 DSG ONE Final Setup ($ENVIRONMENT)"
echo "=================================="

# Step 1: Update Secret Values
log_info "Step 1/3: Updating AWS Secrets..."

read -p "ใส่ Anthropic API Key (sk-...): " ANTHROPIC_KEY
read -p "ใส่ JWT Secret: " JWT_SECRET
read -p "ใส่ API Key: " API_KEY

log_info "Updating API secrets..."
aws secretsmanager update-secret \
  --secret-id "dsg-one-${ENVIRONMENT}-api-secrets" \
  --secret-string "{
    \"ANTHROPIC_API_KEY\": \"$ANTHROPIC_KEY\",
    \"JWT_SECRET\": \"$JWT_SECRET\",
    \"API_KEY\": \"$API_KEY\"
  }" \
  --region "$AWS_REGION" > /dev/null
log_success "API secrets updated"

log_info "Updating database secrets..."
aws secretsmanager update-secret \
  --secret-id "dsg-one-${ENVIRONMENT}-database-secrets" \
  --secret-string '{
    "username": "dsg_admin",
    "password": "change-me-to-strong-password",
    "host": "localhost",
    "port": "5432",
    "dbname": "dsg_one"
  }' \
  --region "$AWS_REGION" > /dev/null
log_success "Database secrets updated"

log_info "Updating OAuth secrets..."
aws secretsmanager update-secret \
  --secret-id "dsg-one-${ENVIRONMENT}-oauth-secrets" \
  --secret-string '{
    "GITHUB_CLIENT_ID": "your-github-client-id",
    "GITHUB_CLIENT_SECRET": "your-github-secret",
    "GOOGLE_CLIENT_ID": "your-google-client-id",
    "GOOGLE_CLIENT_SECRET": "your-google-secret"
  }' \
  --region "$AWS_REGION" > /dev/null
log_success "OAuth secrets updated"

echo ""

# Step 2: Create .env.local
log_info "Step 2/3: Creating .env.local..."

cat > "$PROJECT_DIR/.env.local" << EOF
# DSG ONE Environment Configuration
# Generated by final-setup.sh

ENVIRONMENT=$ENVIRONMENT
AWS_REGION=$AWS_REGION
SECRETS_MANAGER_ENABLED=true

# Application
NODE_ENV=production
LOG_LEVEL=info

# Database
DB_HOST=localhost
DB_PORT=5432
DB_NAME=dsg_one
DB_USER=dsg_admin

# Add API keys as needed
ANTHROPIC_API_KEY=$ANTHROPIC_KEY
JWT_SECRET=$JWT_SECRET
API_KEY=$API_KEY
EOF

log_success ".env.local created at $PROJECT_DIR/.env.local"
cat "$PROJECT_DIR/.env.local" | grep -v "^#" | grep -v "^$"

echo ""

# Step 3: Deploy CDK
log_info "Step 3/3: Deploying CDK Infrastructure..."

cd "$PROJECT_DIR/infra/cdk"

log_info "Installing CDK dependencies..."
npm ci --legacy-peer-deps > /dev/null 2>&1 || npm install --legacy-peer-deps > /dev/null 2>&1
log_success "Dependencies installed"

log_info "Building CDK..."
npm run build > /dev/null 2>&1
log_success "Build complete"

log_info "Synthesizing CloudFormation..."
npx cdk synth --context environment="$ENVIRONMENT" > /dev/null 2>&1
log_success "Synthesis complete"

echo ""
log_warn "⚠️  Ready to deploy CDK stack. This will:"
echo "   - Create/Update CloudFormation stack"
echo "   - Create DynamoDB tables"
echo "   - Setup ECS, Lambda, VPC"
echo "   - Approximate cost: \$10-50/month for dev"
echo ""

read -p "Continue with CDK deployment? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    log_info "Deploying CDK stack..."
    npx cdk deploy \
        --context environment="$ENVIRONMENT" \
        --require-approval never

    log_success "CDK deployment complete!"
else
    log_warn "CDK deployment skipped"
    log_info "Deploy manually when ready:"
    echo "  cd $PROJECT_DIR/infra/cdk"
    echo "  npx cdk deploy --context environment=$ENVIRONMENT --require-approval never"
fi

echo ""
echo "=================================="
log_success "✅ DSG ONE Final Setup Complete!"
echo "=================================="
echo ""
echo "📋 What was done:"
echo "   ✓ Updated Secrets Manager with API keys"
echo "   ✓ Created .env.local configuration"
echo "   ✓ Deployed CDK infrastructure"
echo ""
echo "🔗 Next steps:"
echo "   1. Monitor CloudFormation stack in AWS Console"
echo "   2. Update remaining secret values in AWS Secrets Manager"
echo "   3. Start application: npm run dev"
echo "   4. Check deployment: https://tdealer01-crypto-dsg-control-plane.vercel.app/api/agent/status"
echo ""
echo "📊 Infrastructure deployed to:"
echo "   - Region: $AWS_REGION"
echo "   - Account: 121205961822"
echo "   - Environment: $ENVIRONMENT"
echo "   - Stack: DSGOneStack-$ENVIRONMENT"
