#!/bin/bash

################################################################################
# DSG ONE Complete Setup Script
# Setup: Secrets Manager + Environment Variables + CDK Deploy
################################################################################

set -euo pipefail

# Color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $*"; }
log_success() { echo -e "${GREEN}[✓]${NC} $*"; }
log_error() { echo -e "${RED}[✗]${NC} $*"; exit 1; }

ENVIRONMENT="${1:-dev}"
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

log_info "🚀 Starting DSG ONE Complete Setup ($ENVIRONMENT)"
echo "=================================================="

# Step 1: Verify AWS credentials
log_info "Step 1/4: Verifying AWS credentials..."
if ! aws sts get-caller-identity &> /dev/null; then
    log_error "AWS credentials not configured. Run: aws configure"
fi
AWS_ACCOUNT=$(aws sts get-caller-identity --query Account --output text)
log_success "AWS Account: $AWS_ACCOUNT"

# Step 2: Setup Secrets Manager
log_info "Step 2/4: Setting up AWS Secrets Manager..."
if [ -f "$PROJECT_DIR/scripts/aws-secrets-manager-setup.sh" ]; then
    chmod +x "$PROJECT_DIR/scripts/aws-secrets-manager-setup.sh"
    bash "$PROJECT_DIR/scripts/aws-secrets-manager-setup.sh" "$ENVIRONMENT"
    log_success "Secrets Manager setup completed"
else
    log_error "aws-secrets-manager-setup.sh not found"
fi

# Step 3: Create/Update .env file
log_info "Step 3/4: Creating .env file..."
cat > "$PROJECT_DIR/.env.local" << EOF
# DSG ONE Environment Configuration
# Generated by quick-setup-all.sh

ENVIRONMENT=$ENVIRONMENT
AWS_REGION=us-east-1
SECRETS_MANAGER_ENABLED=true

# Secrets Manager References
# Update these with actual secret values in AWS Secrets Manager console:
# - dsg-one-$ENVIRONMENT-api-secrets
# - dsg-one-$ENVIRONMENT-database-secrets
# - dsg-one-$ENVIRONMENT-oauth-secrets

# Application Configuration
NODE_ENV=production
LOG_LEVEL=info

# Database (from Secrets Manager)
DB_HOST=localhost
DB_PORT=5432
DB_NAME=dsg_one
DB_USER=dsg_admin

# Add other environment variables as needed
EOF

log_success ".env.local created"
cat "$PROJECT_DIR/.env.local"

# Step 4: CDK Deploy
log_info "Step 4/4: Deploying CDK Infrastructure..."
read -p "Continue with CDK deploy? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    cd "$PROJECT_DIR/infra/cdk"

    log_info "Installing CDK dependencies..."
    npm ci --legacy-peer-deps

    log_info "Building CDK..."
    npm run build

    log_info "Synthesizing CloudFormation..."
    npx cdk synth --context environment="$ENVIRONMENT"

    log_info "Deploying CDK stack..."
    npx cdk deploy \
        --context environment="$ENVIRONMENT" \
        --require-approval never

    log_success "CDK deployment completed!"
else
    log_info "CDK deployment skipped. Run manually when ready:"
    echo "  cd $PROJECT_DIR/infra/cdk"
    echo "  npx cdk deploy --context environment=$ENVIRONMENT --require-approval never"
fi

echo ""
echo "=================================================="
log_success "🎉 DSG ONE Setup Complete!"
echo ""
echo "📋 What's been done:"
echo "   ✓ AWS Secrets Manager configured"
echo "   ✓ KMS encryption key created"
echo "   ✓ IAM roles for ECS setup"
echo "   ✓ Environment variables (.env.local) created"
echo "   ✓ CDK infrastructure deployed"
echo ""
echo "📝 Next steps:"
echo "   1. Update secret values in AWS Secrets Manager:"
echo "      https://console.aws.amazon.com/secretsmanager/"
echo "   2. Update API keys in .env.local file"
echo "   3. Deploy application: npm run build && npm run start"
echo ""
echo "🔗 Resources:"
echo "   - Application: https://tdealer01-crypto-dsg-control-plane.vercel.app"
echo "   - AWS Account: $AWS_ACCOUNT"
echo "   - Environment: $ENVIRONMENT"
