#!/usr/bin/env npx tsx
/**
 * One-time Stripe product & price setup for DSG Control Plane.
 *
 * Usage:
 *   STRIPE_SECRET_KEY=sk_test_... npx tsx scripts/stripe-setup.ts
 *
 * This creates the three DSG plans (Pro, Business, Enterprise) with
 * monthly + yearly prices in your Stripe account and prints the env
 * vars you need to add to Vercel / .env.local.
 */

import { getStripeClient, setupStripeProducts } from '../lib/stripe-products';

async function main() {
  console.log('DSG Control Plane — Stripe Product Setup');
  console.log('=========================================\n');

  if (!process.env.STRIPE_SECRET_KEY) {
    console.error('Error: STRIPE_SECRET_KEY environment variable is required.');
    console.error('Usage: STRIPE_SECRET_KEY=sk_test_... npx tsx scripts/stripe-setup.ts');
    process.exit(1);
  }

  const stripe = getStripeClient();

  console.log('Creating products and prices in Stripe...\n');

  const envVars = await setupStripeProducts(stripe);

  console.log('Done! Add these environment variables to your Vercel project or .env.local:\n');
  console.log('# --- Stripe Price IDs (generated by stripe-setup.ts) ---');
  for (const [key, value] of Object.entries(envVars)) {
    console.log(`${key}=${value}`);
  }
  console.log('# --- End Stripe Price IDs ---\n');

  console.log('Next steps:');
  console.log('1. Copy the env vars above into Vercel → Settings → Environment Variables');
  console.log('2. Also set STRIPE_SECRET_KEY and STRIPE_WEBHOOK_SECRET in Vercel');
  console.log('3. Set up a Stripe webhook endpoint at https://your-domain.com/api/billing/webhook');
  console.log('   Events to listen for: checkout.session.completed, customer.subscription.*');
}

main().catch((err) => {
  console.error('Setup failed:', err);
  process.exit(1);
});
