create extension if not exists pgcrypto;

create table if not exists runtime_truth_states (
  id uuid primary key default gen_random_uuid(),
  org_id text not null references organizations(id) on delete cascade,
  agent_id text not null references agents(id) on delete cascade,
  canonical_hash text not null,
  canonical_json jsonb not null,
  created_at timestamptz not null default now(),
  unique (org_id, agent_id, canonical_hash)
);

create table if not exists runtime_approval_requests (
  id uuid primary key default gen_random_uuid(),
  org_id text not null references organizations(id) on delete cascade,
  agent_id text not null references agents(id) on delete cascade,
  approval_key text not null,
  request_payload jsonb not null,
  status text not null default 'pending',
  expires_at timestamptz,
  consumed_at timestamptz,
  revoked_at timestamptz,
  created_at timestamptz not null default now(),
  constraint runtime_approval_requests_status_chk
    check (status in ('pending','consumed','revoked','expired','rejected'))
);

create unique index if not exists idx_runtime_approval_requests_key_pending
  on runtime_approval_requests(org_id, agent_id, approval_key)
  where status = 'pending';

create table if not exists runtime_ledger_entries (
  id uuid primary key default gen_random_uuid(),
  org_id text not null references organizations(id) on delete cascade,
  agent_id text not null references agents(id) on delete cascade,
  request_id uuid references runtime_approval_requests(id) on delete set null,
  execution_id uuid references executions(id) on delete set null,
  truth_state_id uuid references runtime_truth_states(id) on delete set null,
  decision text not null,
  ledger_sequence bigint generated by default as identity,
  truth_sequence bigint not null,
  reason text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint runtime_ledger_entries_decision_chk check (decision in ('ALLOW','STABILIZE','BLOCK'))
);

create unique index if not exists idx_runtime_ledger_truth_sequence
  on runtime_ledger_entries(org_id, agent_id, truth_sequence);

create index if not exists idx_runtime_ledger_created
  on runtime_ledger_entries(org_id, agent_id, created_at desc);

create table if not exists runtime_effects (
  id uuid primary key default gen_random_uuid(),
  org_id text not null references organizations(id) on delete cascade,
  agent_id text not null references agents(id) on delete cascade,
  ledger_entry_id uuid references runtime_ledger_entries(id) on delete set null,
  effect_type text not null,
  status text not null default 'pending',
  payload jsonb not null default '{}'::jsonb,
  result_payload jsonb,
  callback_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint runtime_effects_status_chk check (status in ('pending','succeeded','failed'))
);

create table if not exists runtime_checkpoints (
  id uuid primary key default gen_random_uuid(),
  org_id text not null references organizations(id) on delete cascade,
  agent_id text not null references agents(id) on delete cascade,
  truth_state_id uuid not null references runtime_truth_states(id) on delete cascade,
  latest_ledger_entry_id uuid not null references runtime_ledger_entries(id) on delete cascade,
  checkpoint_hash text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (org_id, agent_id, checkpoint_hash)
);
