-- DSG Encoding Proof persistent replay/idempotency/hash-chain ledger.
-- Service-side writes only. RLS stays enabled with no client policies.

create table if not exists public.dsg_encoding_proofs (
  sequence bigint generated by default as identity primary key,
  organization_id text not null,
  problem_id text not null,
  encoding_type text not null check (encoding_type in ('qubo-v1', 'ising-v1')),
  nonce text not null,
  idempotency_key text not null,
  request_hash text not null check (request_hash ~ '^[0-9a-f]{64}$'),
  encoding_hash text not null check (encoding_hash ~ '^[0-9a-f]{64}$'),
  proof_id text not null,
  proof_hash text not null check (proof_hash ~ '^[0-9a-f]{64}$'),
  previous_proof_hash text not null check (previous_proof_hash ~ '^[0-9a-f]{64}$'),
  proof jsonb not null,
  created_at timestamptz not null default now(),

  constraint dsg_encoding_proofs_org_idempotency_unique
    unique (organization_id, idempotency_key),
  constraint dsg_encoding_proofs_org_nonce_unique
    unique (organization_id, nonce),
  constraint dsg_encoding_proofs_org_proof_hash_unique
    unique (organization_id, proof_hash),
  -- A chain head can have at most one successor. This turns concurrent requests
  -- that read the same head into a deterministic conflict instead of a fork.
  constraint dsg_encoding_proofs_org_previous_hash_unique
    unique (organization_id, previous_proof_hash)
);

create index if not exists dsg_encoding_proofs_org_sequence_idx
  on public.dsg_encoding_proofs (organization_id, sequence desc);

create index if not exists dsg_encoding_proofs_problem_idx
  on public.dsg_encoding_proofs (organization_id, problem_id, sequence desc);

alter table public.dsg_encoding_proofs enable row level security;

comment on table public.dsg_encoding_proofs is
  'Server-managed DSG Encoding Proof ledger. Enforces nonce replay protection, idempotency and a single linear proof-hash chain per organization.';
