-- Generated by DSG App Builder runtime for job 2f3b20b0-824c-4d4a-ae6a-250bd18f3392
-- Goal: สร้างแอปเกม abc เด็ก3ขวบ

create extension if not exists pgcrypto;

create table if not exists generated_app_items (
  id uuid primary key default gen_random_uuid(),
  app_id text not null,
  title text not null,
  completed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists generated_app_items_app_id_created_at_idx
  on generated_app_items(app_id, created_at desc);

alter table generated_app_items enable row level security;
