-- Generated by DSG App Builder runtime for job 080601f5-5269-4819-a064-6b539ee19bc3
-- Goal: สร้างhttps://github.com/tdealer01-crypto/dsg-one-v1/pull/71 โดยให้ผู้ใช้ทำงานหลักได้: เพิ่มข้อมูล, แก้ข้อมูล, ลบข้อมูล, ดูรายการ, ค้นหา, แสดงสถานะ. รูปแบบหน้าจอ: มือถือก่อน, อ่านง่าย, เรียบหรู, ทอง / แดง / เงิน, จอมอนิเตอร์สด. ต้องแสดงเฉพาะข้อมูลจริง มีหลักฐานการทำงาน และไม่ใช้ข้อมูลจำลอง.

create extension if not exists pgcrypto;

create table if not exists generated_app_items (
  id uuid primary key default gen_random_uuid(),
  app_id text not null,
  title text not null,
  completed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists generated_app_items_app_id_created_at_idx
  on generated_app_items(app_id, created_at desc);

alter table generated_app_items enable row level security;
