import type { GraphSnapshot, GraphNodeType, Confidence } from './types';

export function buildReport(graph: GraphSnapshot): string {
  const nodesByType = new Map<GraphNodeType, number>();
  for (const n of graph.nodes) {
    nodesByType.set(n.nodeType, (nodesByType.get(n.nodeType) ?? 0) + 1);
  }

  const edgesByConfidence = new Map<Confidence, number>();
  for (const e of graph.edges) {
    edgesByConfidence.set(e.confidence, (edgesByConfidence.get(e.confidence) ?? 0) + 1);
  }

  // Find god nodes (high degree)
  const degree = new Map<string, number>();
  for (const e of graph.edges) {
    degree.set(e.from, (degree.get(e.from) ?? 0) + 1);
    degree.set(e.to, (degree.get(e.to) ?? 0) + 1);
  }
  const godNodes = Array.from(degree.entries())
    .filter(([, d]) => d > 10)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 10);

  const lines: string[] = [
    '# DSG GraphMap Report',
    '',
    `**Built at**: ${graph.builtAt}`,
    `**Nodes**: ${graph.nodeCount} | **Edges**: ${graph.edgeCount}`,
    '',
    '## Nodes by type',
    '',
  ];

  for (const [type, count] of [...nodesByType.entries()].sort((a, b) => b[1] - a[1])) {
    lines.push(`- \`${type}\`: ${count}`);
  }

  lines.push('', '## Edges by confidence', '');
  for (const [conf, count] of [...edgesByConfidence.entries()].sort()) {
    lines.push(`- \`${conf}\`: ${count}`);
  }

  if (godNodes.length > 0) {
    lines.push('', '## High-degree nodes (god nodes)', '');
    for (const [path, deg] of godNodes) {
      lines.push(`- \`${path}\` — degree ${deg}`);
    }
  }

  if (graph.warnings.length > 0) {
    lines.push('', '## Warnings', '');
    for (const w of graph.warnings) {
      lines.push(`- ${w}`);
    }
  }

  lines.push('', '---', '_Generated by DSG GraphMap Plugin_');

  return lines.join('\n');
}
